server {
    listen 80;
    server_name localhost;

    # Указываем папку внутри контейнера, где лежат наши файлы
    root /usr/share/nginx/html;
    index index.html;

    # Инструкция для правильной отдачи статических файлов (HTML, CSS, JS)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Включаем стандартные логи ошибок
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
